# version: '3.3'
# services:
#     db:
#         image: mvertes/alpine-mongo
#         container_name: 'python-mongo-container'
#         environment:
#             MONGO_INITDB_DATABASE: 'mymongodb'
#             MONGO_INITDB_ROOT_USERNAME: 'user'
#             MONGO_INITDB_ROOT_PASSWORD: 'password'
#         volumes:
#             - ./mongo-volume:/data/db
#             - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
#         ports:
#             - '27017-27019:27017-27019'
#     mongo-express:
#         image: mongo-express
#         restart: always
#         depends_on:
#             - db
#         ports:
#           - 8081:8081
#         environment:
#           ME_CONFIG_MONGODB_ADMINUSERNAME: user
#           ME_CONFIG_MONGODB_ADMINPASSWORD: password
# volumes:
#     my-db:

version: '3.6'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mymongodb
    volumes:
      - docker-data:/data/db
      - ./database/:/docker-entrypoint-initdb.d
    ports:
      - '27017-27019:27017-27019'

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
        - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

volumes:
  docker-data:
    name: mymongodb-data