version: '3.3'
services:
    db:
        image: mvertes/alpine-mongo
        container_name: 'python-mongo-container'
        environment:
            MONGO_INITDB_DATABASE: 'mymongodb'
            MONGO_INITDB_ROOT_USERNAME: 'user'
            MONGO_INITDB_ROOT_PASSWORD: 'password'
        volumes:
            - ./mongo-volume:/data/db
            - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports:
            - '27017-27019:27017-27019'
volumes:
    my-db: